# ~/Awk/add_PE_info.awk
# 18/03/2014
# Takes as input 1) File with gene to gene connections from PE information and 2) Chimeric junction matrix generated by Chimsplice. Add to this matrix the information regarding 
# the support of the junctions by PE information. 

#awk -v fileRef:gene_gene_connections.txt -f ~/Awk/add_PE_info.awk distinct_junctions_nbstaggered_nbtotalsplimappings_withmaxbegandend_samechrstr_okgxorder_dist_ss1_ss2_gnlist1_gnlist2_gnname1_gnname2_bt1_bt2_from_split_mappings_part1overA_part2overB_only_A_B_indiffgn_and_inonegn.txt

## INPUT

# 1) pairs_of_diff_gn_supported_by_pereads_nbpereads.txt
# 13 SNORD116 65
# 17 NGS 273
# 19 SNORD116 8

# 2)distinct_junctions_nbstaggered_nbtotalsplimappings_withmaxbegandend_samechrstr_okgxorder_dist_ss1_ss2_gnlist1_gnlist2_gnname1_gnname2_bt1_bt2_from_split_mappings_part1overA_part2overB_only_A_B_indiffgn_and_inonegn.txt

#chr11_12883797_.:chr11_17229395_- 3 3 12883828 17229427 1 1 4345598 NA AC TEAD1, PIK3C2A, TEAD1, PIK3C2A, . . 
#chr16_85023910_.:chr12_123444869_. 1 1 85023932 123444840 0 NA NA NA NA ZDHHC7, ABCB9, ZDHHC7, ABCB9, . . 
#chr21_42880008_-:chr21_39817544_- 25 25 39817494 42880055 1 1 3062464 AC CT TMPRSS2, ERG, TMPRSS2, ERG, . . 


## OUTPUT

#chr11_12883797_.:chr11_17229395_- 3 3 12883828 17229427 1 1 4345598 NA AC TEAD1, PIK3C2A, TEAD1, PIK3C2A, . . TEAD1-PIK3C2A:4,
#chr16_85023910_.:chr12_123444869_. 1 1 85023932 123444840 0 NA NA NA NA ZDHHC7, ABCB9, ZDHHC7, ABCB9, . . ZDHHC7-ABCB9:11,
#chr21_42880008_-:chr21_39817544_- 25 25 39817494 42880055 1 1 3062464 AC CT TMPRSS2, ERG, TMPRSS2, ERG, . . TMPRSS2-ERG:190,



BEGIN{while (getline < fileRef >0)
	{
		PE[$1"-"$2]=$3
	}
}
{
	split($11,a,",");
	split($12,b,","); 
	s=""; 
	for (gnIdA in a)
	{
		for (gnIdB in b)
		{
			if (PE[a[gnIdA]"-"b[gnIdB]]!="")
			{
				s=(s)(a[gnIdA]"-"b[gnIdB])(":")(PE[a[gnIdA]"-"b[gnIdB]])(",");
			}
			else
			{
				if (PE[b[gnIdB]"-"a[gnIdA]]!="")
				{
					s=(s)(a[gnIdA]"-"b[gnIdB])(":")(PE[b[gnIdB]"-"a[gnIdA]])(",");
				}
			}
		}
	}
	if (s=="")
	{	
		s=".";
	} 
	print $0, s;
} 
